#
name: Trivy Scan to OWASP Juice shop

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  workflow_dispatch:

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Docker
        run: docker pull bkimminich/juice-shop

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "bkimminich/juice-shop"
          output: "scan-result"
          scan-type: "image"
          format: "table"
          exit-code: "0"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          scanners: "license, secret vule misconfig"
        #   flag: must be one of ["vuln" "misconfig" "secret" "license"]

      - uses: actions/upload-artifact@v4
        with:
          name: scan-result
          path: scan-result
